# Generated by Django 5.1.6 on 2025-02-21 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('gym_equipment', 'Gym Equipment'), ('clothing', 'Clothing'), ('shoes', 'Shoes'), ('supplements', 'Supplements'), ('sports_gear', 'Sports Gear')], max_length=100)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
